STORE_PATH = '~/Downloads/store/'

# DATABASE
DB_USERNAME = 'student'
DB_PASSWORD = '12345'
DB_SERVER = '127.0.0.1'
DB_DATABASE = 'test'
SQLALCHEMY_DATABASE_URI = 'mysql://' + DB_USERNAME + ':' + DB_PASSWORD + '@' + DB_SERVER + ':3306/' + DB_DATABASE
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = True
